import type {
  ActionDirectionSnapshot,
  CalculationResultDTO,
  SingleBoltEvaluationResponse,
  SingleBoltPreviewResponse,
  VisualizationSnapshot,
} from "../src/api/contracts";

const point = (x: string, y: string, z: string) => ({ x, y, z, unit: "in" });
const direction = (x: string, y: string, z: string) => ({ x, y, z });

function action(
  component: ActionDirectionSnapshot["component"],
  kind: ActionDirectionSnapshot["kind"],
  signedValue: string | null,
  sense: ActionDirectionSnapshot["sense"],
  axis = direction("1", "0", "0"),
): ActionDirectionSnapshot {
  return {
    component,
    kind,
    axis,
    reference_point_id: "action:action-1:reference",
    frame_id: "MEMBER_LOCAL:member-a",
    signed_value: signedValue,
    unit: kind === "LINEAR" ? "kip" : "kip-in",
    sense,
    is_zero: sense === "ZERO",
    member_end: "START",
    axial_loading_sense: component === "FX" ? "TENSION" : null,
  };
}

export function visualizationFixture(): VisualizationSnapshot {
  const positive = [
    action("FX", "LINEAR", null, null),
    action("FY", "LINEAR", null, null, direction("0", "1", "0")),
    action("FZ", "LINEAR", null, null, direction("0", "0", "1")),
    action("MX", "ROTATIONAL", null, null),
    action("MY", "ROTATIONAL", null, null, direction("0", "1", "0")),
    action("MZ", "ROTATIONAL", null, null, direction("0", "0", "1")),
  ];
  const applied = [
    action("FX", "LINEAR", "-0.7", "NEGATIVE", direction("-1", "0", "0")),
    action("FY", "LINEAR", "0", "ZERO", direction("0", "1", "0")),
    action("FZ", "LINEAR", "0.2", "POSITIVE", direction("0", "0", "1")),
    action("MX", "ROTATIONAL", "0", "ZERO"),
    action("MY", "ROTATIONAL", "0", "ZERO", direction("0", "1", "0")),
    action("MZ", "ROTATIONAL", "1", "POSITIVE", direction("0", "0", "1")),
  ];
  return {
    snapshot_version: "1.3.0-draft",
    assembly_id: "benchmark-assembly",
    interface_id: "interface-1",
    bolt_group_id: "bolt-group-1",
    bolt_location_id: "bolt-1",
    unit_system: "US_CUSTOMARY",
    length_unit: "in",
    force_unit: "kip",
    moment_unit: "kip-in",
    frames: [
      {
        id: "GLOBAL",
        label: "Global",
        kind: "GLOBAL",
        owner_id: null,
        frame: {
          origin: point("0", "0", "0"),
          x_axis: direction("1", "0", "0"),
          y_axis: direction("0", "1", "0"),
          z_axis: direction("0", "0", "1"),
        },
        inspection: { orthonormal: true, right_handed: true },
      },
      {
        id: "MEMBER_LOCAL:member-a",
        label: "Brace local",
        kind: "MEMBER_LOCAL",
        owner_id: "member-a",
        frame: {
          origin: point("0", "0", "0"),
          x_axis: direction("1", "0", "0"),
          y_axis: direction("0", "1", "0"),
          z_axis: direction("0", "0", "1"),
        },
        inspection: { orthonormal: true, right_handed: true },
      },
      {
        id: "MEMBER_LOCAL:member-b",
        label: "Column local",
        kind: "MEMBER_LOCAL",
        owner_id: "member-b",
        frame: {
          origin: point("1", "1", "0"),
          x_axis: direction("0.7071067811865476", "0.7071067811865476", "0"),
          y_axis: direction("-0.7071067811865476", "0.7071067811865476", "0"),
          z_axis: direction("0", "0", "1"),
        },
        inspection: { orthonormal: false, right_handed: true },
      },
      {
        id: "INTERFACE_LOCAL:interface-1",
        label: "Interface local",
        kind: "INTERFACE_LOCAL",
        owner_id: "interface-1",
        frame: {
          origin: point("2", "0.1875", "0"),
          x_axis: direction("0", "0", "1"),
          y_axis: direction("1", "0", "0"),
          z_axis: direction("0", "1", "0"),
        },
        inspection: { orthonormal: true, right_handed: true },
      },
      {
        id: "BOLT_GROUP_LOCAL:bolt-group-1",
        label: "Bolt group local",
        kind: "BOLT_GROUP_LOCAL",
        owner_id: "bolt-group-1",
        frame: {
          origin: point("2", "0.1875", "0"),
          x_axis: direction("0", "0", "1"),
          y_axis: direction("1", "0", "0"),
          z_axis: direction("0", "1", "0"),
        },
        inspection: { orthonormal: true, right_handed: true },
      },
    ],
    components: [],
    primitives: [
      {
        id: "member-a:LEG_1",
        label: "Angle leg 1",
        kind: "BOX",
        owner_id: "member-a",
        frame_id: "MEMBER_LOCAL:member-a",
        physical_element_id: "LEG_1",
        material_region_id: "LEG_1",
        center: point("2", "0", "-0.1875"),
        x_axis: direction("1", "0", "0"),
        y_axis: direction("0", "1", "0"),
        z_axis: direction("0", "0", "1"),
        parameters: [
          { name: "x_start", value: "0" },
          { name: "x_end", value: "4" },
          { name: "min_y", value: "-1.5" },
          { name: "max_y", value: "1.5" },
          { name: "min_z", value: "-0.375" },
          { name: "max_z", value: "0" },
        ],
        points: [],
        resolution_status: "EXACT",
      },
      {
        id: "member-a:deferred",
        label: "Deferred corner zone",
        kind: "DEFERRED_RECTANGLE",
        owner_id: "member-a",
        frame_id: "MEMBER_LOCAL:member-a",
        physical_element_id: null,
        material_region_id: null,
        center: point("2", "0", "0"),
        x_axis: direction("1", "0", "0"),
        y_axis: direction("0", "1", "0"),
        z_axis: direction("0", "0", "1"),
        parameters: [
          { name: "x_start", value: "0" },
          { name: "x_end", value: "4" },
          { name: "min_y", value: "-0.1" },
          { name: "max_y", value: "0.1" },
          { name: "min_z", value: "-0.1" },
          { name: "max_z", value: "0.1" },
        ],
        points: [],
        resolution_status: "DEFERRED",
      },
    ],
    view_extension_primitives: [],
    material_directions: [
      {
        id: "member-a:LEG_1:material",
        component_id: "member-a",
        physical_element_id: "LEG_1",
        material_region_id: "LEG_1",
        origin: point("2", "0", "0"),
        lengthwise: direction("1", "0", "0"),
        crosswise: direction("0", "1", "0"),
        through_thickness: direction("0", "0", "1"),
        resolution_status: "EXACT",
        reason: null,
      },
      {
        id: "member-b:steel",
        component_id: "member-b",
        physical_element_id: "WEB",
        material_region_id: "WEB",
        origin: point("0", "0", "0"),
        lengthwise: null,
        crosswise: null,
        through_thickness: null,
        resolution_status: "NOT_APPLICABLE",
        reason: "No fixed directions",
      },
    ],
    interface_zones: [
      {
        id: "first-zone",
        label: "First zone",
        interface_id: "interface-1",
        side: "FIRST",
        participant_kind: "MEMBER",
        participant_id: "member-a",
        patch_id: "patch-a",
        geometry_kind: "PLANAR_RECTANGLE",
        center: point("2", "0.1875", "0"),
        normal: direction("0", "0", "1"),
        corners: [
          point("1", "-1", "0"),
          point("3", "-1", "0"),
          point("3", "1", "0"),
          point("1", "1", "0"),
        ],
        parameters: [],
      },
      {
        id: "second-zone",
        label: "W flange contact zone",
        interface_id: "interface-1",
        side: "SECOND",
        participant_kind: "MEMBER",
        participant_id: "member-b",
        patch_id: "patch-b",
        geometry_kind: "PLANAR_RECTANGLE",
        center: point("2", "0.1875", "0"),
        normal: direction("-1", "0", "0"),
        corners: [
          point("2", "-1", "-1"),
          point("2", "1", "-1"),
          point("2", "1", "1"),
          point("2", "-1", "1"),
        ],
        parameters: [],
      },
    ],
    connection_orientation: {
      connection_side: "EXTERIOR",
      connected_leg: "LEG_1",
      outstanding_leg_side: "POSITIVE_INTERFACE_Z",
      supporting_member_id: "member-b",
      selected_flange_element_id: "TOP_FLANGE",
      selected_flange_surface_id: "patch-b",
      selected_flange_surface_role: "POSITIVE_THICKNESS_FACE",
      connected_member_id: "member-a",
      selected_angle_surface_id: "patch-angle",
      selected_angle_surface_role: "NEGATIVE_THICKNESS_FACE",
      selected_contact_normal: direction("-1", "0", "0"),
      brace_to_column_directed_angle_degrees: "45",
      plan_angle_degrees: "0",
      interference_classifications: [],
      interference_participant_ids: [],
      interference_physical_element_ids: [],
      geometry_valid: true,
    },
    bolt: {
      bolt_group_id: "bolt-group-1",
      bolt_location_id: "bolt-1",
      center: point("2", "0.1875", "0"),
      axis: direction("0", "0", "1"),
      stack_start: point("2", "0.1875", "-0.375"),
      stack_end: point("2", "0.1875", "0.5"),
      bolt_diameter: "0.5",
      holes: [
        {
          id: "hole-a",
          participant_id: "member-a",
          physical_element_id: "LEG_1",
          start: point("2", "0.1875", "-0.375"),
          end: point("2", "0.1875", "0"),
          diameter: "0.563",
        },
      ],
      washers: [
        {
          id: "washer-head",
          location: "UNDER_HEAD",
          start: point("2", "0.1875", "-0.425"),
          end: point("2", "0.1875", "-0.375"),
          outside_diameter: "1",
        },
        {
          id: "washer-nut",
          location: "UNDER_NUT",
          start: point("2", "0.1875", "0.5"),
          end: point("2", "0.1875", "0.55"),
          outside_diameter: "1",
        },
      ],
    },
    reference_points: [
      {
        id: "joint-origin",
        label: "Joint origin",
        kind: "JOINT_ORIGIN",
        owner_id: "benchmark-assembly",
        position: point("0", "0", "0"),
        frame_id: "JOINT_LOCAL:benchmark-assembly",
        member_end: null,
        connected: null,
        provenance: null,
      },
      {
        id: "member-a:start",
        label: "Brace START",
        kind: "MEMBER_END",
        owner_id: "member-a",
        position: point("0", "0", "0"),
        frame_id: "MEMBER_LOCAL:member-a",
        member_end: "START",
        connected: true,
        provenance: "PHYSICAL_LONGITUDINAL_BOUNDARY_PLANE",
      },
      {
        id: "member-a:end",
        label: "Brace END",
        kind: "MEMBER_END",
        owner_id: "member-a",
        position: point("4", "0", "0"),
        frame_id: "MEMBER_LOCAL:member-a",
        member_end: "END",
        connected: false,
        provenance: "PHYSICAL_LONGITUDINAL_BOUNDARY_PLANE",
      },
      {
        id: "bolt:bolt-1:center",
        label: "Selected bolt center",
        kind: "BOLT_CENTER",
        owner_id: "bolt-1",
        position: point("2", "0.1875", "0"),
        frame_id: "BOLT_GROUP_LOCAL:bolt-group-1",
        member_end: null,
        connected: null,
        provenance: null,
      },
      {
        id: "action:action-1:reference",
        label: "Applied action reference",
        kind: "MEMBER_CONNECTED_END",
        owner_id: "member-a",
        position: point("0", "0", "0"),
        frame_id: "MEMBER_LOCAL:member-a",
        member_end: "START",
        connected: true,
        provenance: "MEMBER_CONNECTED_END_SECTION_DATUM",
      },
    ],
    positive_action_directions: positive,
    applied_action_directions: applied,
  };
}

function result(
  checkId: string,
  comparison: string,
  calculated: boolean,
): CalculationResultDTO {
  return {
    plan: {
      check_id: checkId,
      limit_state: checkId.includes("net") ? "NET_SECTION_TENSION" : "PIN_BEARING",
      component_id: "member-b",
      layer_id: "layer-B",
      source_section: "8.3.2.4",
      source_equation: calculated ? "8-7" : null,
      readiness_status: calculated ? "READY" : "NOT_APPLICABLE",
      selected_direction_family: calculated ? "TRANSVERSE" : null,
      theta_degrees: calculated ? "45" : null,
      required_property_kind: calculated ? "FNT_T" : null,
      qualification_flags: calculated ? ["ENGINEERING_REVIEW_REQUIRED"] : [],
      warnings: [],
      required: calculated,
    },
    availability: calculated ? "CALCULATED" : "NOT_APPLICABLE",
    numerical_comparison: comparison,
    demand: calculated ? { value: "0.7", unit: "kip" } : null,
    nominal_resistance: calculated ? { value: "2", unit: "kip" } : null,
    design_resistance: calculated ? { value: "1", unit: "kip" } : null,
    utilization: calculated ? "0.7" : null,
    equation_trace: calculated
      ? {
          bearing_property: { property_kind: "FNT_T" },
          factor_trace: {
            c_delta: "1",
            c_lap: "0.6",
            phi: "0.6",
            lambda_factor: "1",
          },
        }
      : null,
    source_snapshot: { standard_name: "ASCE/SEI 74-23", section: "8.3.2.4" },
    warnings: calculated ? ["engineering review"] : [],
  };
}

export function responseFixture(): SingleBoltEvaluationResponse {
  return {
    api_transport_schema_version: "0.5.0-draft",
    project_schema_version: "0.1.0-draft",
    calculation_contract_version: "2.1A-RC2",
    calculation_engine_version: "0.1.0.dev1",
    engineering_rule_set_version: "asce74-23-ch8-single-bolt-rc2.dev1",
    calculation_id: "benchmark-assembly:calculation",
    assembly_id: "benchmark-assembly",
    interface_id: "interface-1",
    bolt_group_id: "bolt-group-1",
    bolt_location_id: "bolt-1",
    load_combination_id: "LC-1",
    unit_system: "US_CUSTOMARY",
    calculation_fingerprint: "abc123",
    material_assignments: [],
    fastener: {},
    resolved_layers: [
      {
        layer_id: "layer-A",
        participant_id: "member-a",
        physical_element_id: "LEG_1",
        material_region_id: "LEG_1",
        code_mapping: { theta_degrees: "0", direction_family: "LONGITUDINAL" },
      },
      {
        layer_id: "layer-B",
        participant_id: "member-b",
        physical_element_id: "TOP_FLANGE",
        material_region_id: "FLANGES",
        code_mapping: { theta_degrees: "45", direction_family: "TRANSVERSE" },
      },
    ],
    source_action_trace: {},
    resolved_demand: {},
    plans: [],
    results: [result("interface-1:bolt-1:layer-B:net_tension", "PASS", true), result("not-applicable", "NOT_EVALUATED", false)],
    aggregate_status: "SECTION_2_3_2_QUALIFICATION_REQUIRED",
    governing_check_ids: ["interface-1:bolt-1:layer-B:net_tension"],
    qualification_flags: ["ENGINEERING_REVIEW_REQUIRED"],
    issues: [
      {
        code: "SECTION_2_3_2_QUALIFICATION_REQUIRED",
        message: "Whole-connection qualification remains required.",
        identities: [],
      },
    ],
    warnings: [],
    source_references: [],
    visualization: visualizationFixture(),
  };
}

export function failureResponseFixture(): SingleBoltEvaluationResponse {
  const response = responseFixture();
  response.aggregate_status = "KNOWN_NUMERICAL_FAILURE";
  response.qualification_flags = [];
  response.results = [result("failure", "FAIL", true)];
  response.issues = [];
  return response;
}

export function previewResponseFixture(): SingleBoltPreviewResponse {
  const design = responseFixture();
  return {
    preview_schema_version: "0.2.0-draft",
    project_schema_version: design.project_schema_version,
    calculation_id: design.calculation_id,
    assembly_id: design.assembly_id,
    interface_id: design.interface_id,
    bolt_group_id: design.bolt_group_id,
    bolt_location_id: design.bolt_location_id,
    load_combination_id: design.load_combination_id,
    unit_system: design.unit_system,
    geometry_status: "PREVIEW_VALID",
    geometry_issues: [],
    resolved_layers: design.resolved_layers,
    material_relationships: [
      {
        layer_id: "layer-B",
        theta_degrees: "45",
        direction_family: "TRANSVERSE",
        direction_interpretation_id: "NEAREST_CANONICAL_DIRECTION",
      },
    ],
    source_action_trace: design.source_action_trace,
    visualization: design.visualization,
    design_check_ready: true,
    design_check_blocking_reasons: [],
  };
}
